# This is a basic workflow to help you get started with Actions

name: Build Containers

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build mubs
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          platforms: linux/arm64
          tags: adrianlucrececeleste/mubs:latest
      -
        name: Build mubs-cc
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          platforms: linux/amd64
          file: {context}/cross-compile.Dockerfile
          tags: adrianlucrececeleste/mubs-cc:latest