# This is a basic workflow to help you get started with Actions

name: Build Containers

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/adriankoshka/mubs
            ghcr.io/adriankoshka/mubs-cc
          # generate Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build mubs
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          platforms: linux/arm64
          tags: ghcr.io/adriankoshka/mubs:latest
      -
        name: Build mubs-cc
        id: docker_cross_build
        uses: docker/build-push-action@v2
        with:
          push: false
          file: 'cross-compile.Dockerfile'
          tags: ghcr.io/adriankoshka/mubs-cc:latest